# Generated by Django 5.2.11 on 2026-02-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
